LG-669 Retry once when Twilio request times out
**Why**: We have noticed a few instances of Twilio requests timing out,
about 10 per day on average, and Twilio support recommended retrying
the requests to see if they still time out. I also added some logging
temporarily so we can give Twilio support more info if the retries
don't work.

To measure the impact of this change, we will check the frequency of the
analytics event with name "Twilio Phone Validation Failed" and following
event_properties:
```ruby
{
   error: "[HTTP 4815162342] 4815162342 : timeout",
   code: 4815162342
}
```