Fix `TypeError` for OTP jobs
**Why**:
* Full error:
```
TypeError: no implicit conversion of ActiveSupport::Duration into String
```
* We were not getting this in our tests because they passed time
* In real world, we pass a string bc jobs can only handle string args