LG-6193: Integrate IdV app personal key step into proofing flow (feature-flagged) (#6269)
* LG-6193: Integrate IdV app personal key step into proofing flow

**Why**: So that a user can functionally complete the proofing process using the new IdV app.

changelog: Upcoming Features, Identity Verification, Add personal key step screen

* Move completion behavior to pack

* Add spec for VerifyFlow

* Revert feature specs covering personal key page

deal with it later

* Fix VerifyFlow spec

Maybe bug with testing-library? Seems to struggle querying by role "TypeError: style.getPropertyValue is not a function"

* Stub applicant for VerifyController spec

copied from personal_key_controller_spec.rb